# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-15 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, null=True)),
                ('occurences', models.IntegerField(null=True)),
            ],
        ),
    ]
